#!/bin/sh -ex

#ensure datafiles (eg. innodb) are created
/etc/init.d/mysql start
/etc/init.d/mysql stop

# enable cgi
a2enmod cgi

# remove unrequired webcp icons (all except those named) 
cd /var/www/images
find . -type f ! -name "adminer.png" ! -name "shell.png" ! -name "tab.png" ! -name "webmin.png" -delete

#get gpg file for sury.org php packages
wget -O /etc/apt/trusted.gpg.d/php.sury.gpg https://packages.sury.org/php/apt.gpg
